// Generated by dts-bundle v0.7.3

declare module 'trie-prefix-tree' {

    /**
      * Created by user on 2018/6/8/008.
      */
    import { ITrieRow, create } from 'trie/create';

    interface ITrie
    {
        tree(): ReturnType<typeof create>;
        dump(spacer?): string;

        addWord(word: string): this;
        removeWord(word: string): this;
        hasWord(word: string): boolean;

        getWords(sorted?: boolean): string[];

        isPrefix(prefix: string): boolean;

        getPrefix(strPrefix: string, sorted?: boolean): string[];
        countPrefix(strPrefix: string): number;

        getAnagrams(letters: string): string[];
        getSubAnagrams(letters: string): string[];
    }

    function trie(input: string[]): ITrie;

    export = trie
}

declare module 'trie-prefix-tree/create' {

    /**
      * Created by user on 2018/6/8/008.
      */
    interface ITrieRow {
        [k: string]: ITrieRow,
        // @ts-ignore
        "$": 1,
    }

    export function create(input: string[]): {
        [k: string]: ITrieRow
    };
}

